In [1]:
include("PyrochloreGeometry.jl")
import .PyrochloreGeometry as geom
using LinearAlgebra

In [11]:
nsample = 100000
L = 100000
Klist = rand(-L:L,nsample,3)*π/(L)
b = 2 .*geom.pyro

W = zeros(ComplexF64,4,4)
for mu=1:4, nu=1:4
    f = k -> exp(-1im/2 * k' *(b[mu] + b[nu])/8) 
    W[mu,nu] = sum( map( f , eachrow(Klist) ) )/nsample
end
W

4×4 Matrix{ComplexF64}:
 0.729155+0.000906693im  0.900283+0.000535394im  …  0.900948-0.000988845im
 0.900283+0.000535394im  0.730606-0.000895045im     0.900735-0.00214639im
 0.900735+0.00214639im   0.900948+0.000988845im     0.900283-0.000535394im
 0.900948-0.000988845im  0.900735-0.00214639im      0.730923-0.00298943im

In [12]:
[(b[mu] - b[nu]) for mu=1:4, nu=1:4]/2 /8

4×4 Matrix{StaticArraysCore.SVector{3, Float64}}:
 [0.0, 0.0, 0.0]      [0.0, 0.25, 0.25]   …  [0.25, 0.25, 0.0]
 [0.0, -0.25, -0.25]  [0.0, 0.0, 0.0]        [0.25, 0.0, -0.25]
 [-0.25, 0.0, -0.25]  [-0.25, 0.25, 0.0]     [0.0, 0.25, -0.25]
 [-0.25, -0.25, 0.0]  [-0.25, 0.0, 0.25]     [0.0, 0.0, 0.0]

In [13]:
lat = geom.PyroFCC(1)

Main.PyrochloreGeometry.PyroFCC(1, StaticArraysCore.SVector{3, Int64}[[0, 0, 0], [0, 4, 4], [4, 0, 4], [4, 4, 0], [2, 2, 2], [2, 6, 6], [6, 2, 6], [6, 6, 2]], StaticArraysCore.SVector{3, Int64}[[0, 0, 0], [0, 4, 4], [4, 0, 4], [4, 4, 0]], StaticArraysCore.SVector{3, Int64}[[1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, 1], [1, 5, 5], [1, 3, 3], [-1, 5, 3], [-1, 3, 5], [5, 1, 5], [5, -1, 3], [3, 1, 3], [3, -1, 5], [5, 5, 1], [5, 3, -1], [3, 5, -1], [3, 3, 1]])

4×4 Matrix{Float64}:
 0.729769  0.900316  0.900316  0.900316
 0.900316  0.729769  0.900316  0.900316
 0.900316  0.900316  0.729769  0.900316
 0.900316  0.900316  0.900316  0.729769