In [2]:
include("src/PyrochloreGeometry.jl")
import .PyrochloreGeometry as geom
using LinearAlgebra

In [17]:
nsample = 1000000
L = 100000
Klist = rand(-L:L,nsample,3)/L *π
b = 2 .*geom.pyro

W = zeros(ComplexF64,4,4)
for mu=1:4, nu=1:4
    f = k -> exp(-1im/2 * k' *(b[mu] - b[nu])/8) 
    W[mu,nu] = sum( map( f , eachrow(Klist) ) )/nsample
end
W

4×4 Matrix{ComplexF64}:
      1.0+0.0im           0.81047-0.000914408im  …  0.810371-0.000824677im
  0.81047+0.000914408im       1.0+0.0im             0.810971+0.000116386im
 0.810307+0.000985923im  0.811021+0.000100799im     0.810714+0.000276465im
 0.810371+0.000824677im  0.810971-0.000116386im          1.0+0.0im

In [4]:
[(b[mu] - b[nu]) for mu=1:4, nu=1:4]/2 /8

4×4 Matrix{StaticArraysCore.SVector{3, Float64}}:
 [0.0, 0.0, 0.0]      [0.0, 0.25, 0.25]   …  [0.25, 0.25, 0.0]
 [0.0, -0.25, -0.25]  [0.0, 0.0, 0.0]        [0.25, 0.0, -0.25]
 [-0.25, 0.0, -0.25]  [-0.25, 0.25, 0.0]     [0.0, 0.25, -0.25]
 [-0.25, -0.25, 0.0]  [-0.25, 0.0, 0.25]     [0.0, 0.0, 0.0]

In [16]:
 ((8/2π)*sin(π/4))^2

0.8105694691387021

4×4 Matrix{Float64}:
 0.729769  0.900316  0.900316  0.900316
 0.900316  0.729769  0.900316  0.900316
 0.900316  0.900316  0.729769  0.900316
 0.900316  0.900316  0.900316  0.729769